# Generated by Django 4.2 on 2023-04-05 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(default=0)),
                ('name', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Haryana', 'Haryana'), ('Maharashtra', 'Maharashtra'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Punjab', 'Punjab'), ('West Bengal', 'West Bengal'), ('Rajasthan', 'Rajasthan'), ('Goa', 'Goa'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Delhi', 'Delhi'), ('Kerala', 'Kerala')], max_length=100)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
